services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - '${DB_VOLUME}:/var/lib/mysql'

  api:
    build: .
    ports:
      - '${PORT}:10101'
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data:
